name: Build Lib TSS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-libs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run libtss-docker-build script
        run: |
          scripts/libtss-docker-build

      - name: Upload .build directory as artifact
        uses: actions/upload-artifact@v3
        with:
          name: libtss
          path: .build
